//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        private static Entities _context;
        public Entities()
            : base("name=Entities")
        {
        }
        public static Entities GetContext()
        {
            if (_context == null)
                _context = new Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Аудитории> Аудитории { get; set; }
        public virtual DbSet<Виды_занятий> Виды_занятий { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Дисциплина> Дисциплина { get; set; }
        public virtual DbSet<Дни_недели> Дни_недели { get; set; }
        public virtual DbSet<Пары> Пары { get; set; }
        public virtual DbSet<Расписание> Расписание { get; set; }
        public virtual DbSet<Четность_недели> Четность_недели { get; set; }
        public virtual DbSet<Список_пользователей> Список_пользователей { get; set; }
    }
}
