//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int Код_расписания { get; set; }
        public Nullable<int> День_недели { get; set; }
        public Nullable<int> Четность { get; set; }
        public Nullable<int> Пара { get; set; }
        public Nullable<int> Группа { get; set; }
        public Nullable<int> Дисциплина { get; set; }
        public Nullable<int> Вид_занятия { get; set; }
        public Nullable<int> Аудитория { get; set; }
    
        public virtual Аудитории Аудитории { get; set; }
        public virtual Виды_занятий Виды_занятий { get; set; }
        public virtual Группы Группы { get; set; }
        public virtual Дисциплина Дисциплина1 { get; set; }
        public virtual Дни_недели Дни_недели { get; set; }
        public virtual Пары Пары { get; set; }
        public virtual Четность_недели Четность_недели { get; set; }
    }
}
